In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import seaborn as sns
import statsmodels.api as sm

raw = pd.read_csv('./데이터/서울시_침수대피소.csv',encoding='utf-8')

In [26]:
raw

,R_SEQ_NO,CD_AREA,NO_EQUP_SE,SD_NM,SGG_NM,CD_EQUP,GB_ACMD,EQUP_NM,RDNMADR_CD,BDONG_CD,HDONG_CD,LOC_SFPR_A,SECT_EQUP,QTY_CPTY,XCORD,YCORD,XX,YY,CD_GUBUN
0,3751,1156000000,416,서울특별시,영등포구,1,학교,양화중학교,1156012100100480000037220,1.156012e+09,1156060500,서울특별시 영등포구 당산로 56(문래동3가),725,279,126.89605,37.51977,190810.63564,546703.31996,긴급
1,3800,1159000000,11,서울특별시,동작구,1,학교,서울신상도초등학교,1159010200102040333026309,1.159010e+09,1159054000,서울특별시 동작구 장승배기로 14(상도동),530,203,126.94406,37.50028,195053.81344,544536.21780,안전
2,3798,1156000000,461,서울특별시,영등포구,14,"공공시설(국·공립도서관, 공립병원, 시·도민회관, 구민회관 주민체육시설, 노인병원,...",푸드뱅크마켓3호점,1156013200147290000009413,1.156013e+09,1156068000,서울특별시 영등포구 신길로8길 7(신길동),62,24,126.90933,37.49573,191982.11213,544034.28136,안전
3,3763,1156000000,445,서울특별시,영등포구,3,경로당,구립문래제1경로당,1156012100100730001000001,1.156012e+09,1156060500,서울특별시 영등포구 문래로20길 7(문래동3가),201,77,126.89420,37.51846,190646.47678,546558.46883,안전
4,3799,1156000000,421,서울특별시,영등포구,1,학교,서울영문초등학교,1156012400100130000037490,1.156012e+09,1156060500,서울특별시 영등포구 문래로 56(문래동6가),720,277,126.88754,37.51960,190058.54739,546685.18169,긴급
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,14349,1130500000,79,서울특별시,강북구,6,교회,평강교회,1130510200104120018017575,1.130510e+09,1130559000,서울특별시 강북구 한천로 995(번동),891,343,127.03010,37.63713,202656.45977,559724.77961,긴급
1121,14256,1130500000,70,서울특별시,강북구,1,학교,송중초등학교,1130510100100940001035142,1.130510e+09,1130554500,서울특별시 강북구 오현로 9(미아동),752,289,127.03136,37.61672,202768.43496,557459.13878,긴급
1122,14358,1130500000,89,서울특별시,강북구,6,교회,성북교회,1130510300102630002009676,1.130510e+09,1130562000,서울특별시 강북구 한천로 1125(수유동),668,257,127.01900,37.64502,201676.60294,560599.65486,긴급
1123,14359,1130500000,93,서울특별시,강북구,14,"공공시설(국·공립도서관, 공립병원, 시·도민회관, 구민회관 주민체육시설, 노인병원,...",강북청소년센터,1130510300105350380005826,1.130510e+09,1130564500,서울특별시 강북구 4.19로 74(수유동),596,229,127.00642,37.64583,200566.24926,560689.23415,안전
1124,14350,1130500000,80,서울특별시,강북구,6,교회,주영광교회,1130510200104610066016059,1.130510e+09,1130559000,서울특별시 강북구 한천로 1004(번동),496,191,127.03001,37.63831,202649.05499,559855.59296,긴급

In [27]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   R_SEQ_NO    1125 non-null   int64
 1   CD_AREA     1125 non-null   int64
 2   NO_EQUP_SE  1125 non-null   int64
 3   SD_NM       1125 non-null   object
 4   SGG_NM      1125 non-null   object
 5   CD_EQUP     1125 non-null   int64
 6   GB_ACMD     1125 non-null   object
 7   EQUP_NM     1125 non-null   object
 8   RDNMADR_CD  1124 non-null   object
 9   BDONG_CD    1124 non-null   float64
 10  HDONG_CD    1125 non-null   int64
 11  LOC_SFPR_A  1125 non-null   object
 12  SECT_EQUP   1125 non-null   int64
 13  QTY_CPTY    1125 non-null   int64
 14  XCORD       1125 non-null   float64
 15  YCORD       1125 non-null   float64
 16  XX          1125 non-null   float64
 17  YY          1125 non-null   float64
 18  CD_GUBUN    1125 non-null   object
dtypes: float64(5), int64(7), object(7)
memory usage: 167.1+ KB

In [28]:
raw.isnull().sum()

R_SEQ_NO      0
CD_AREA       0
NO_EQUP_SE    0
SD_NM         0
SGG_NM        0
CD_EQUP       0
GB_ACMD       0
EQUP_NM       0
RDNMADR_CD    1
BDONG_CD      1
HDONG_CD      0
LOC_SFPR_A    0
SECT_EQUP     0
QTY_CPTY      0
XCORD         0
YCORD         0
XX            0
YY            0
CD_GUBUN      0
dtype: int64

In [31]:
raw.columns

Index(['R_SEQ_NO', 'CD_AREA', 'NO_EQUP_SE', 'SD_NM', 'SGG_NM', 'CD_EQUP',
       'GB_ACMD', 'EQUP_NM', 'RDNMADR_CD', 'BDONG_CD', 'HDONG_CD',
       'LOC_SFPR_A', 'SECT_EQUP', 'QTY_CPTY', 'XCORD', 'YCORD', 'XX', 'YY',
       'CD_GUBUN'],
      dtype='object')

In [29]:
raw.head()

,R_SEQ_NO,CD_AREA,NO_EQUP_SE,SD_NM,SGG_NM,CD_EQUP,GB_ACMD,EQUP_NM,RDNMADR_CD,BDONG_CD,HDONG_CD,LOC_SFPR_A,SECT_EQUP,QTY_CPTY,XCORD,YCORD,XX,YY,CD_GUBUN
0,3751,1156000000,416,서울특별시,영등포구,1,학교,양화중학교,1156012100100480000037220,1.156012e+09,1156060500,서울특별시 영등포구 당산로 56(문래동3가),725,279,126.89605,37.51977,190810.63564,546703.31996,긴급
1,3800,1159000000,11,서울특별시,동작구,1,학교,서울신상도초등학교,1159010200102040333026309,1.159010e+09,1159054000,서울특별시 동작구 장승배기로 14(상도동),530,203,126.94406,37.50028,195053.81344,544536.21780,안전
2,3798,1156000000,461,서울특별시,영등포구,14,"공공시설(국·공립도서관, 공립병원, 시·도민회관, 구민회관 주민체육시설, 노인병원,...",푸드뱅크마켓3호점,1156013200147290000009413,1.156013e+09,1156068000,서울특별시 영등포구 신길로8길 7(신길동),62,24,126.90933,37.49573,191982.11213,544034.28136,안전
3,3763,1156000000,445,서울특별시,영등포구,3,경로당,구립문래제1경로당,1156012100100730001000001,1.156012e+09,1156060500,서울특별시 영등포구 문래로20길 7(문래동3가),201,77,126.89420,37.51846,190646.47678,546558.46883,안전
4,3799,1156000000,421,서울특별시,영등포구,1,학교,서울영문초등학교,1156012400100130000037490,1.156012e+09,1156060500,서울특별시 영등포구 문래로 56(문래동6가),720,277,126.88754,37.51960,190058.54739,546685.18169,긴급

In [32]:
raw = raw.rename(columns = {
    'SGG_NM' : '자치구',
    'GB_ACMD' : '장소_종류',
    'EQUP_NM' : '대피소_이름',
    'QTY_CPTY' : '수용인원',
    'BDONG_CD' : '법정동_코드',
    'XCORD' : '경도',
    'YCORD' : '위도',
    'CD_GUBUN' : '대피소_분류_구분'
})

In [34]:
raw.head(3)

,R_SEQ_NO,CD_AREA,NO_EQUP_SE,SD_NM,자치구,CD_EQUP,장소_종류,대피소_이름,RDNMADR_CD,법정동_코드,HDONG_CD,LOC_SFPR_A,SECT_EQUP,수용인원,경도,위도,XX,YY,대피소_분류_구분
0,3751,1156000000,416,서울특별시,영등포구,1,학교,양화중학교,1156012100100480000037220,1.156012e+09,1156060500,서울특별시 영등포구 당산로 56(문래동3가),725,279,126.89605,37.51977,190810.63564,546703.31996,긴급
1,3800,1159000000,11,서울특별시,동작구,1,학교,서울신상도초등학교,1159010200102040333026309,1.159010e+09,1159054000,서울특별시 동작구 장승배기로 14(상도동),530,203,126.94406,37.50028,195053.81344,544536.21780,안전
2,3798,1156000000,461,서울특별시,영등포구,14,"공공시설(국·공립도서관, 공립병원, 시·도민회관, 구민회관 주민체육시설, 노인병원,...",푸드뱅크마켓3호점,1156013200147290000009413,1.156013e+09,1156068000,서울특별시 영등포구 신길로8길 7(신길동),62,24,126.90933,37.49573,191982.11213,544034.28136,안전

In [35]:
raw= raw[['자치구','장소_종류','대피소_이름','법정동_코드','수용인원','위도','경도','대피소_분류_구분']]

In [36]:
raw.to_csv('./데이터/대피소_최종.csv',index=False)